/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: robot_telemetry.proto */

#ifndef PROTOBUF_C_robot_5ftelemetry_2eproto__INCLUDED
#define PROTOBUF_C_robot_5ftelemetry_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Robot__V1__Header Robot__V1__Header;
typedef struct Robot__V1__Vec3f Robot__V1__Vec3f;
typedef struct Robot__V1__MotorState Robot__V1__MotorState;
typedef struct Robot__V1__TelemetryState Robot__V1__TelemetryState;


/* --- enums --- */


/* --- messages --- */

struct  Robot__V1__Header
{
  ProtobufCMessage base;
  /*
   * ex: "robot_sim"
   */
  char *robot_id;
  /*
   * ns (monotonic ou epoch)
   */
  uint64_t timestamp_ns;
  /*
   * contador incremental (opcional)
   */
  uint32_t seq;
};
#define ROBOT__V1__HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robot__v1__header__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0 }


struct  Robot__V1__Vec3f
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
};
#define ROBOT__V1__VEC3F__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robot__v1__vec3f__descriptor) \
    , 0, 0, 0 }


struct  Robot__V1__MotorState
{
  ProtobufCMessage base;
  /*
   * "motor1" / "motor2"
   */
  char *motor_id;
  /*
   * contador bruto do encoder
   */
  uint32_t tics;
  /*
   * RPM (motor, antes da caixa)
   */
  int32_t rpm;
  /*
   * °C
   */
  int32_t temperature_c;
  /*
   * mV
   */
  int32_t voltage_power_stage_mv;
  /*
   * mA
   */
  int32_t current_power_stage_ma;
};
#define ROBOT__V1__MOTOR_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robot__v1__motor_state__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0 }


/*
 * Snapshot pronto pra dashboard
 */
struct  Robot__V1__TelemetryState
{
  ProtobufCMessage base;
  Robot__V1__Header *header;
  /*
   * IMU
   */
  /*
   * "imu0"
   */
  char *imu_id;
  /*
   * g
   */
  Robot__V1__Vec3f *acc_g;
  /*
   * deg/s
   */
  Robot__V1__Vec3f *gyro_dps;
  /*
   * Tilt
   */
  /*
   * "tilt0"
   */
  char *tilt_id;
  /*
   * deg
   */
  Robot__V1__Vec3f *tilt_deg;
  /*
   * 0 normal, 1 reinitializing
   */
  uint32_t tilt_status;
  /*
   * Motors
   */
  Robot__V1__MotorState *motor1;
  Robot__V1__MotorState *motor2;
};
#define ROBOT__V1__TELEMETRY_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robot__v1__telemetry_state__descriptor) \
    , NULL, (char *)protobuf_c_empty_string, NULL, NULL, (char *)protobuf_c_empty_string, NULL, 0, NULL, NULL }


/* Robot__V1__Header methods */
void   robot__v1__header__init
                     (Robot__V1__Header         *message);
size_t robot__v1__header__get_packed_size
                     (const Robot__V1__Header   *message);
size_t robot__v1__header__pack
                     (const Robot__V1__Header   *message,
                      uint8_t             *out);
size_t robot__v1__header__pack_to_buffer
                     (const Robot__V1__Header   *message,
                      ProtobufCBuffer     *buffer);
Robot__V1__Header *
       robot__v1__header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   robot__v1__header__free_unpacked
                     (Robot__V1__Header *message,
                      ProtobufCAllocator *allocator);
/* Robot__V1__Vec3f methods */
void   robot__v1__vec3f__init
                     (Robot__V1__Vec3f         *message);
size_t robot__v1__vec3f__get_packed_size
                     (const Robot__V1__Vec3f   *message);
size_t robot__v1__vec3f__pack
                     (const Robot__V1__Vec3f   *message,
                      uint8_t             *out);
size_t robot__v1__vec3f__pack_to_buffer
                     (const Robot__V1__Vec3f   *message,
                      ProtobufCBuffer     *buffer);
Robot__V1__Vec3f *
       robot__v1__vec3f__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   robot__v1__vec3f__free_unpacked
                     (Robot__V1__Vec3f *message,
                      ProtobufCAllocator *allocator);
/* Robot__V1__MotorState methods */
void   robot__v1__motor_state__init
                     (Robot__V1__MotorState         *message);
size_t robot__v1__motor_state__get_packed_size
                     (const Robot__V1__MotorState   *message);
size_t robot__v1__motor_state__pack
                     (const Robot__V1__MotorState   *message,
                      uint8_t             *out);
size_t robot__v1__motor_state__pack_to_buffer
                     (const Robot__V1__MotorState   *message,
                      ProtobufCBuffer     *buffer);
Robot__V1__MotorState *
       robot__v1__motor_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   robot__v1__motor_state__free_unpacked
                     (Robot__V1__MotorState *message,
                      ProtobufCAllocator *allocator);
/* Robot__V1__TelemetryState methods */
void   robot__v1__telemetry_state__init
                     (Robot__V1__TelemetryState         *message);
size_t robot__v1__telemetry_state__get_packed_size
                     (const Robot__V1__TelemetryState   *message);
size_t robot__v1__telemetry_state__pack
                     (const Robot__V1__TelemetryState   *message,
                      uint8_t             *out);
size_t robot__v1__telemetry_state__pack_to_buffer
                     (const Robot__V1__TelemetryState   *message,
                      ProtobufCBuffer     *buffer);
Robot__V1__TelemetryState *
       robot__v1__telemetry_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   robot__v1__telemetry_state__free_unpacked
                     (Robot__V1__TelemetryState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Robot__V1__Header_Closure)
                 (const Robot__V1__Header *message,
                  void *closure_data);
typedef void (*Robot__V1__Vec3f_Closure)
                 (const Robot__V1__Vec3f *message,
                  void *closure_data);
typedef void (*Robot__V1__MotorState_Closure)
                 (const Robot__V1__MotorState *message,
                  void *closure_data);
typedef void (*Robot__V1__TelemetryState_Closure)
                 (const Robot__V1__TelemetryState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor robot__v1__header__descriptor;
extern const ProtobufCMessageDescriptor robot__v1__vec3f__descriptor;
extern const ProtobufCMessageDescriptor robot__v1__motor_state__descriptor;
extern const ProtobufCMessageDescriptor robot__v1__telemetry_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_robot_5ftelemetry_2eproto__INCLUDED */
