/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: robot_telemetry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "robot_telemetry.pb-c.h"
void   robot__v1__header__init
                     (Robot__V1__Header         *message)
{
  static const Robot__V1__Header init_value = ROBOT__V1__HEADER__INIT;
  *message = init_value;
}
size_t robot__v1__header__get_packed_size
                     (const Robot__V1__Header *message)
{
  assert(message->base.descriptor == &robot__v1__header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t robot__v1__header__pack
                     (const Robot__V1__Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &robot__v1__header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t robot__v1__header__pack_to_buffer
                     (const Robot__V1__Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &robot__v1__header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Robot__V1__Header *
       robot__v1__header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Robot__V1__Header *)
     protobuf_c_message_unpack (&robot__v1__header__descriptor,
                                allocator, len, data);
}
void   robot__v1__header__free_unpacked
                     (Robot__V1__Header *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &robot__v1__header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   robot__v1__vec3f__init
                     (Robot__V1__Vec3f         *message)
{
  static const Robot__V1__Vec3f init_value = ROBOT__V1__VEC3F__INIT;
  *message = init_value;
}
size_t robot__v1__vec3f__get_packed_size
                     (const Robot__V1__Vec3f *message)
{
  assert(message->base.descriptor == &robot__v1__vec3f__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t robot__v1__vec3f__pack
                     (const Robot__V1__Vec3f *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &robot__v1__vec3f__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t robot__v1__vec3f__pack_to_buffer
                     (const Robot__V1__Vec3f *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &robot__v1__vec3f__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Robot__V1__Vec3f *
       robot__v1__vec3f__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Robot__V1__Vec3f *)
     protobuf_c_message_unpack (&robot__v1__vec3f__descriptor,
                                allocator, len, data);
}
void   robot__v1__vec3f__free_unpacked
                     (Robot__V1__Vec3f *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &robot__v1__vec3f__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   robot__v1__motor_state__init
                     (Robot__V1__MotorState         *message)
{
  static const Robot__V1__MotorState init_value = ROBOT__V1__MOTOR_STATE__INIT;
  *message = init_value;
}
size_t robot__v1__motor_state__get_packed_size
                     (const Robot__V1__MotorState *message)
{
  assert(message->base.descriptor == &robot__v1__motor_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t robot__v1__motor_state__pack
                     (const Robot__V1__MotorState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &robot__v1__motor_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t robot__v1__motor_state__pack_to_buffer
                     (const Robot__V1__MotorState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &robot__v1__motor_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Robot__V1__MotorState *
       robot__v1__motor_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Robot__V1__MotorState *)
     protobuf_c_message_unpack (&robot__v1__motor_state__descriptor,
                                allocator, len, data);
}
void   robot__v1__motor_state__free_unpacked
                     (Robot__V1__MotorState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &robot__v1__motor_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   robot__v1__telemetry_state__init
                     (Robot__V1__TelemetryState         *message)
{
  static const Robot__V1__TelemetryState init_value = ROBOT__V1__TELEMETRY_STATE__INIT;
  *message = init_value;
}
size_t robot__v1__telemetry_state__get_packed_size
                     (const Robot__V1__TelemetryState *message)
{
  assert(message->base.descriptor == &robot__v1__telemetry_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t robot__v1__telemetry_state__pack
                     (const Robot__V1__TelemetryState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &robot__v1__telemetry_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t robot__v1__telemetry_state__pack_to_buffer
                     (const Robot__V1__TelemetryState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &robot__v1__telemetry_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Robot__V1__TelemetryState *
       robot__v1__telemetry_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Robot__V1__TelemetryState *)
     protobuf_c_message_unpack (&robot__v1__telemetry_state__descriptor,
                                allocator, len, data);
}
void   robot__v1__telemetry_state__free_unpacked
                     (Robot__V1__TelemetryState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &robot__v1__telemetry_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor robot__v1__header__field_descriptors[3] =
{
  {
    "robot_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__Header, robot_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp_ns",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__Header, timestamp_ns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__Header, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned robot__v1__header__field_indices_by_name[] = {
  0,   /* field[0] = robot_id */
  2,   /* field[2] = seq */
  1,   /* field[1] = timestamp_ns */
};
static const ProtobufCIntRange robot__v1__header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor robot__v1__header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "robot.v1.Header",
  "Header",
  "Robot__V1__Header",
  "robot.v1",
  sizeof(Robot__V1__Header),
  3,
  robot__v1__header__field_descriptors,
  robot__v1__header__field_indices_by_name,
  1,  robot__v1__header__number_ranges,
  (ProtobufCMessageInit) robot__v1__header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor robot__v1__vec3f__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__Vec3f, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__Vec3f, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__Vec3f, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned robot__v1__vec3f__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange robot__v1__vec3f__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor robot__v1__vec3f__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "robot.v1.Vec3f",
  "Vec3f",
  "Robot__V1__Vec3f",
  "robot.v1",
  sizeof(Robot__V1__Vec3f),
  3,
  robot__v1__vec3f__field_descriptors,
  robot__v1__vec3f__field_indices_by_name,
  1,  robot__v1__vec3f__number_ranges,
  (ProtobufCMessageInit) robot__v1__vec3f__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor robot__v1__motor_state__field_descriptors[6] =
{
  {
    "motor_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__MotorState, motor_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tics",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__MotorState, tics),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rpm",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__MotorState, rpm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature_c",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__MotorState, temperature_c),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage_power_stage_mv",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__MotorState, voltage_power_stage_mv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_power_stage_ma",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__MotorState, current_power_stage_ma),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned robot__v1__motor_state__field_indices_by_name[] = {
  5,   /* field[5] = current_power_stage_ma */
  0,   /* field[0] = motor_id */
  2,   /* field[2] = rpm */
  3,   /* field[3] = temperature_c */
  1,   /* field[1] = tics */
  4,   /* field[4] = voltage_power_stage_mv */
};
static const ProtobufCIntRange robot__v1__motor_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor robot__v1__motor_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "robot.v1.MotorState",
  "MotorState",
  "Robot__V1__MotorState",
  "robot.v1",
  sizeof(Robot__V1__MotorState),
  6,
  robot__v1__motor_state__field_descriptors,
  robot__v1__motor_state__field_indices_by_name,
  1,  robot__v1__motor_state__number_ranges,
  (ProtobufCMessageInit) robot__v1__motor_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor robot__v1__telemetry_state__field_descriptors[9] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__TelemetryState, header),
    &robot__v1__header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imu_id",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__TelemetryState, imu_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acc_g",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__TelemetryState, acc_g),
    &robot__v1__vec3f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_dps",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__TelemetryState, gyro_dps),
    &robot__v1__vec3f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tilt_id",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__TelemetryState, tilt_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tilt_deg",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__TelemetryState, tilt_deg),
    &robot__v1__vec3f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tilt_status",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__TelemetryState, tilt_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "motor1",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__TelemetryState, motor1),
    &robot__v1__motor_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "motor2",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Robot__V1__TelemetryState, motor2),
    &robot__v1__motor_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned robot__v1__telemetry_state__field_indices_by_name[] = {
  2,   /* field[2] = acc_g */
  3,   /* field[3] = gyro_dps */
  0,   /* field[0] = header */
  1,   /* field[1] = imu_id */
  7,   /* field[7] = motor1 */
  8,   /* field[8] = motor2 */
  5,   /* field[5] = tilt_deg */
  4,   /* field[4] = tilt_id */
  6,   /* field[6] = tilt_status */
};
static const ProtobufCIntRange robot__v1__telemetry_state__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 20, 4 },
  { 30, 7 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor robot__v1__telemetry_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "robot.v1.TelemetryState",
  "TelemetryState",
  "Robot__V1__TelemetryState",
  "robot.v1",
  sizeof(Robot__V1__TelemetryState),
  9,
  robot__v1__telemetry_state__field_descriptors,
  robot__v1__telemetry_state__field_indices_by_name,
  4,  robot__v1__telemetry_state__number_ranges,
  (ProtobufCMessageInit) robot__v1__telemetry_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
